apiVersion: kiali.io/v1alpha1
kind: Kiali
metadata:
  name: kiali
  namespace: {{ .Release.Namespace }}
  labels:
    release: {{ .Release.Name }}
annotations:
  ansible.operator-sdk/reconcile-period: "0s"
spec:
  ###################################################################
  # For details about the supported settings, 
  # see https://github.com/kiali/kiali/blob/v1.0/operator/deploy/kiali/kiali_cr.yaml"
  istio_namespace: {{ .Release.Namespace }}
  auth:
    strategy: {{ .Values.kiali.dashboard.auth.strategy }}
  deployment:
    image_name: {{ .Values.kiali.hub }}/kiali
    image_pull_policy: {{ .Values.global.imagePullPolicy }}
    image_version: {{ .Values.kiali.tag }}
    namespace: {{ .Release.Namespace }}
    {{- if .Values.kiali.accessibleNamespaces }}
    accessible_namespaces: {{ .Values.kiali.accessibleNamespaces }}
    {{- end }}
    ingress_enabled: {{ .Values.kiali.ingress.enabled }}
    verbose_mode: 3
    view_only_mode: {{ .Values.kiali.dashboard.viewOnlyMode }}
    affinity:
    {{- include "nodeaffinity" . | indent 3 }}
    {{- include "podAntiAffinity" . | indent 3 }}
    {{- if .Values.kiali.tolerations }}
    tolerations:
    {{ toYaml .Values.kiali.tolerations | indent 3 }}
    {{- end }}
    {{- if .Values.kiali.createDemoSecret }}
    secret_name: {{ .Values.kiali.dashboard.secretName }}
    {{- end }}
  tracing:
    url: {{ .Values.kiali.dashboard.jaegerURL }}
  grafana:
    url: {{ .Values.kiali.dashboard.grafanaURL }}
  prometheus:
    url: {{ .Values.kiali.prometheusAddr }}
  {{- if .Values.kiali.security.enabled }}
  identity:
    cert_file: {{ .Values.kiali.security.cert_file }}
    private_key_file: {{ .Values.kiali.security.private_key_file }}
  {{- end}}
  server:
    port: 20001
    {{- if .Values.kiali.contextPath }}
    web_root: {{ .Values.kiali.contextPath }}
    {{- end }}
---
{{- if .Values.kiali.createDemoSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.kiali.dashboard.secretName }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: kiali
    release: {{ .Release.Name }}
type: Opaque
data:
  username: YWRtaW4=   # admin
  passphrase: YWRtaW4= # admin
{{- end }}
