apiVersion: v1
kind: Service
metadata:
  name: zipkin
  namespace: {{ .Release.Namespace }}
  labels:
    app: tracing
    release: {{ .Release.Name }}
spec:
  type: {{ .Values.tracing.service.type }}
  ports:
    - port: {{ .Values.tracing.service.externalPort }}
      targetPort: 9411
      protocol: TCP
      name: {{ .Values.tracing.service.name }}
  selector:
    app: tracing
---
{{- if ne .Values.tracing.provider "opencensus"}}
apiVersion: v1
kind: Service
metadata:
  name: tracing
  namespace: {{ .Release.Namespace }}
  annotations:
    {{- range $key, $val := .Values.tracing.service.annotations }}
    {{ $key }}: {{ $val | quote }}
    {{- end }}
  labels:
    app: tracing
    release: {{ .Release.Name }}
spec:
  ports:
    - name: http-query
      port: 80
      protocol: TCP
{{ if eq .Values.tracing.provider "jaeger" }}
      targetPort: 16686
{{ else }}
      targetPort: 9411
{{ end}}
  selector:
    app: tracing
{{- end }}

{{- if eq .Values.tracing.provider "jaeger" }}
apiVersion: v1
kind: Service
metadata:
  name: jaeger-query
  namespace: {{ .Release.Namespace }}
  annotations:
    {{- range $key, $val := .Values.tracing.service.annotations }}
    {{ $key }}: {{ $val | quote }}
    {{- end }}
  labels:
    app: tracing
    jaeger-infra: jaeger-service
    release: {{ .Release.Name }}
spec:
  ports:
    - name: query-http
      port: 16686
      protocol: TCP
      targetPort: 16686
  selector:
    app: tracing
---
apiVersion: v1
kind: Service
metadata:
  name: jaeger-collector
  namespace: {{ .Release.Namespace }}
  labels:
    app: tracing
    jaeger-infra: collector-service
    release: {{ .Release.Name }}
spec:
  ports:
  - name: jaeger-collector-tchannel
    port: 14267
    protocol: TCP
    targetPort: 14267
  - name: jaeger-collector-http
    port: 14268
    targetPort: 14268
    protocol: TCP
  selector:
    app: tracing
  type: ClusterIP
{{- end }}
